spring:
    application:
        name: graphql-psql3

    datasource:
        url: jdbc:postgresql://localhost:5442/testdb
        username: postgres
        password: skilltest
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true
            
    graphql:
        graphiql:
            enabled: true
    
